build:
  image: niltonvasques/android-emulator:1.3
  privileged: true
  commands:
    - cp -a /drone/.gradle /root/ && rm -Rf /drone/.gradle
    - hostname -I
    - wget http://server:8000/goku.gif
    # start_emulator
    # ./gradlew check --daemon -PdisablePreDex --stacktrace
    # ./gradlew assembleDebugAndroidTest --daemon -PdisablePreDex --stacktrace
    # wait_emulator && unlock_emulator
    # ./gradlew cC --daemon -PdisablePreDex --stacktrace
    # cp -a /root/.gradle /drone/
cache:
  mount:
    - /drone/.gradle
compose:
  server:
    image: niltonvasques/gif-sample-server
