build:
  image: niltonvasques/android-emulator:1.3
  privileged: true
  commands:
    - cp -a /drone/.gradle /root/ && rm -Rf /drone/.gradle
    - ./tests.sh
    - cp -a /root/.gradle /drone/
cache:
  mount:
    - /drone/.gradle
compose:
  server:
    image: niltonvasques/gif-sample-server
