build:
  image: niltonvasques/android-emulator:1.2
  privileged: true
  commands:
    - cp -a /drone/.gradle /root/ && rm -Rf /drone/.gradle
    - echo "no" | emulator64-x86 -avd test -noaudio -no-window -gpu off -verbose -qemu -usbdevice tablet &
    - adb wait-for-device
    - A=$(adb shell getprop sys.boot_completed | tr -d '\r'); sec=1; while [ "$A" != "1" ]; do echo "waiting emulator boot for "$sec" seconds"; sleep 2; sec=$((sec + 2)); A=$(adb shell getprop sys.boot_completed | tr -d '\r'); done
    - ./gradlew check --daemon -PdisablePreDex --stacktrace
    - ./gradlew assembleDebugAndroidTest --daemon -PdisablePreDex --stacktrace
    - if [ $(adb shell dumpsys input_method | grep mInteractive=false | wc -l) -eq 1 ]; then adb shell input keyevent 82; fi
    - ./gradlew cC --daemon -PdisablePreDex --stacktrace
    - cp -a /root/.gradle /drone/
cache:
  mount:
    - /drone/.gradle
