build:
  image: niltonvasques/android-emulator:latest
  commands:
    - cp -a /drone/.gradle /root && rm -Rf /drone/.gradle
    - echo "no" | emulator64-arm -avd test -noaudio -no-window -gpu off -verbose -qemu -usbdevice tablet &
    - adb wait-for-device
    - A=$(adb shell getprop sys.boot_completed | tr -d '\r'); sec=1; while [ "$A" != "1" ]; do echo "waiting emulator boot for "$sec" seconds"; sleep 2; sec=$((sec + 2)); A=$(adb shell getprop sys.boot_completed | tr -d '\r'); done
    - ./gradlew check --daemon -PdisablePreDex --stacktrace
    - ./gradlew assembleDebugAndroidTest --daemon -PdisablePreDex --stacktrace
    - adb shell input keyevent 82
    - ./gradlew cC --daemon -PdisablePreDex --stacktrace
    - cp -a /root/.gradle /drone
cache:
  mount:
    - .gradle
